-- DELETE DATA

DELETE FROM doctor CASCADE;
DELETE FROM paciente CASCADE;
DELETE FROM asistente CASCADE;
DELETE FROM especialidad CASCADE;
DELETE FROM doctor_especialidad CASCADE;
DELETE FROM tipo_consulta CASCADE;
DELETE FROM consulta CASCADE;
DELETE FROM tratamiento CASCADE;
DELETE FROM expediente CASCADE;
DELETE FROM ginecologia CASCADE;
DELETE FROM nutricion CASCADE;
DELETE FROM sexologia CASCADE;
DELETE FROM psicologia CASCADE;
DELETE FROM suenio CASCADE;





